### ISSUE TITLE
Problem with obtaining certain annotations

### ISSUE THREAD

**Issue by jakalssj3** [rcavalcante/annotatr#43] opened 2021-06-11 15:15 UTC
The below code I use to download annotations with annotatr works only partially:
```
annotations <- c("hg19_cpgs","hg19_genes_promoters")
promoters.GR <- annotatr::build_annotations(genome='hg19', annotations=c(annotations[2]))
cpgs.GR <- annotatr::build_annotations(genome='hg19', annotations=c(annotations[1]))
```
Specifically, there is no problem to get annotations of promoters, but when trying to get cpg annotations, the following error occurs:
```
Error in UseMethod("filter_") : no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
```

What could be the reason for this?

I'm using R version 3.6.3 and annotatr version 1.12.1

**Comment by rcavalcante** [comment] 2021-06-11 16:17
Hi,

Thanks for using annotatr. I couldn't replicate your error using a Docker image with a similar environment (R 3.6.2 and annotar 1.12.1):

https://hub.docker.com/repository/docker/rcavalcante/bioconductor_docker (RELEASE_3_10 tag)

I wonder if perhaps you have some packages loaded that are causing the error because of NAMESPACE issues... I'm not sure if the code you provided above is after only doing `library(annotatr)` or if you've loaded other packages too. Do you get the same error with just `library(annotatr)`?

Here is my `devtools::session_info()`:

```
> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Debian GNU/Linux 10 (buster)
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2021-06-11                  

─ Packages ───────────────────────────────────────────────────────────────────
 package                           * version  date       lib source        
 AnnotationDbi                     * 1.48.0   2019-10-29 [1] Bioconductor  
 AnnotationHub                       2.18.0   2019-10-29 [1] Bioconductor  
 annotatr                          * 1.12.1   2019-11-12 [1] Bioconductor  
 askpass                             1.1      2019-01-13 [1] CRAN (R 3.6.2)
 assertthat                          0.2.1    2019-03-21 [1] CRAN (R 3.6.2)
 backports                           1.1.5    2019-10-02 [1] CRAN (R 3.6.2)
 Biobase                           * 2.46.0   2019-10-29 [1] Bioconductor  
 BiocFileCache                       1.10.2   2019-11-08 [1] Bioconductor  
 BiocGenerics                      * 0.32.0   2019-10-29 [1] Bioconductor  
 BiocManager                       * 1.30.10  2019-11-16 [1] CRAN (R 3.6.2)
 BiocParallel                        1.20.1   2019-12-21 [1] Bioconductor  
 BiocVersion                         3.10.1   2019-06-06 [1] Bioconductor  
 biomaRt                             2.42.1   2020-03-26 [1] Bioconductor  
 Biostrings                          2.54.0   2019-10-29 [1] Bioconductor  
 bit                                 1.1-15.2 2020-02-10 [1] CRAN (R 3.6.2)
 bit64                               0.9-7    2017-05-08 [1] CRAN (R 3.6.2)
 bitops                              1.0-6    2013-08-17 [1] CRAN (R 3.6.2)
 blob                                1.2.1    2020-01-20 [1] CRAN (R 3.6.2)
 BSgenome                            1.54.0   2019-10-29 [1] Bioconductor  
 callr                               3.4.2    2020-02-12 [1] CRAN (R 3.6.2)
 cli                                 2.0.2    2020-02-28 [1] CRAN (R 3.6.2)
 colorspace                          1.4-1    2019-03-18 [1] CRAN (R 3.6.2)
 crayon                              1.3.4    2017-09-16 [1] CRAN (R 3.6.2)
 curl                                4.3      2019-12-02 [1] CRAN (R 3.6.2)
 DBI                                 1.1.0    2019-12-15 [1] CRAN (R 3.6.2)
 dbplyr                              1.4.2    2019-06-17 [1] CRAN (R 3.6.2)
 DelayedArray                        0.12.2   2020-01-06 [1] Bioconductor  
 desc                                1.2.0    2018-05-01 [1] CRAN (R 3.6.2)
 devtools                            2.2.2    2020-02-17 [1] CRAN (R 3.6.2)
 digest                              0.6.25   2020-02-23 [1] CRAN (R 3.6.2)
 dplyr                               0.8.5    2020-03-07 [1] CRAN (R 3.6.2)
 ellipsis                            0.3.0    2019-09-20 [1] CRAN (R 3.6.2)
 fansi                               0.4.1    2020-01-08 [1] CRAN (R 3.6.2)
 fastmap                             1.0.1    2019-10-08 [1] CRAN (R 3.6.2)
 fs                                  1.3.2    2020-03-05 [1] CRAN (R 3.6.2)
 GenomeInfoDb                      * 1.22.0   2019-10-29 [1] Bioconductor  
 GenomeInfoDbData                    1.2.2    2020-03-27 [1] Bioconductor  
 GenomicAlignments                   1.22.1   2019-11-12 [1] Bioconductor  
 GenomicFeatures                   * 1.38.2   2020-02-15 [1] Bioconductor  
 GenomicRanges                     * 1.38.0   2019-10-29 [1] Bioconductor  
 ggplot2                             3.3.0    2020-03-05 [1] CRAN (R 3.6.2)
 glue                                1.3.2    2020-03-12 [1] CRAN (R 3.6.2)
 gtable                              0.3.0    2019-03-25 [1] CRAN (R 3.6.2)
 hms                                 0.5.3    2020-01-08 [1] CRAN (R 3.6.2)
 htmltools                           0.4.0    2019-10-04 [1] CRAN (R 3.6.2)
 httpuv                              1.5.2    2019-09-11 [1] CRAN (R 3.6.2)
 httr                                1.4.1    2019-08-05 [1] CRAN (R 3.6.2)
 interactiveDisplayBase              1.24.0   2019-10-29 [1] Bioconductor  
 IRanges                           * 2.20.2   2020-01-13 [1] Bioconductor  
 later                               1.0.0    2019-10-04 [1] CRAN (R 3.6.2)
 lattice                             0.20-40  2020-02-19 [2] CRAN (R 3.6.2)
 lifecycle                           0.2.0    2020-03-06 [1] CRAN (R 3.6.2)
 magrittr                            1.5      2014-11-22 [1] CRAN (R 3.6.2)
 Matrix                              1.2-18   2019-11-27 [2] CRAN (R 3.6.2)
 matrixStats                         0.56.0   2020-03-13 [1] CRAN (R 3.6.2)
 memoise                             1.1.0    2017-04-21 [1] CRAN (R 3.6.2)
 mime                                0.9      2020-02-04 [1] CRAN (R 3.6.2)
 munsell                             0.5.0    2018-06-12 [1] CRAN (R 3.6.2)
 openssl                             1.4.1    2019-07-18 [1] CRAN (R 3.6.2)
 org.Hs.eg.db                      * 3.10.0   2020-03-27 [1] Bioconductor  
 pillar                              1.4.3    2019-12-20 [1] CRAN (R 3.6.2)
 pkgbuild                            1.0.6    2019-10-09 [1] CRAN (R 3.6.2)
 pkgconfig                           2.0.3    2019-09-22 [1] CRAN (R 3.6.2)
 pkgload                             1.0.2    2018-10-29 [1] CRAN (R 3.6.2)
 plyr                                1.8.6    2020-03-03 [1] CRAN (R 3.6.2)
 prettyunits                         1.1.1    2020-01-24 [1] CRAN (R 3.6.2)
 processx                            3.4.2    2020-02-09 [1] CRAN (R 3.6.2)
 progress                            1.2.2    2019-05-16 [1] CRAN (R 3.6.2)
 promises                            1.1.0    2019-10-04 [1] CRAN (R 3.6.2)
 ps                                  1.3.2    2020-02-13 [1] CRAN (R 3.6.2)
 purrr                               0.3.3    2019-10-18 [1] CRAN (R 3.6.2)
 R6                                  2.4.1    2019-11-12 [1] CRAN (R 3.6.2)
 rappdirs                            0.3.1    2016-03-28 [1] CRAN (R 3.6.2)
 Rcpp                                1.0.4    2020-03-17 [1] CRAN (R 3.6.2)
 RCurl                               1.98-1.1 2020-01-19 [1] CRAN (R 3.6.2)
 readr                               1.3.1    2018-12-21 [1] CRAN (R 3.6.2)
 regioneR                            1.18.1   2020-01-14 [1] Bioconductor  
 remotes                             2.1.1    2020-02-15 [1] CRAN (R 3.6.2)
 reshape2                            1.4.3    2017-12-11 [1] CRAN (R 3.6.2)
 rlang                               0.4.5    2020-03-01 [1] CRAN (R 3.6.2)
 rprojroot                           1.3-2    2018-01-03 [1] CRAN (R 3.6.2)
 Rsamtools                           2.2.3    2020-02-23 [1] Bioconductor  
 RSQLite                             2.2.0    2020-01-07 [1] CRAN (R 3.6.2)
 rtracklayer                         1.46.0   2019-10-29 [1] Bioconductor  
 S4Vectors                         * 0.24.3   2020-01-18 [1] Bioconductor  
 scales                              1.1.0    2019-11-18 [1] CRAN (R 3.6.2)
 sessioninfo                         1.1.1    2018-11-05 [1] CRAN (R 3.6.2)
 shiny                               1.4.0.2  2020-03-13 [1] CRAN (R 3.6.2)
 stringi                             1.4.6    2020-02-17 [1] CRAN (R 3.6.2)
 stringr                             1.4.0    2019-02-10 [1] CRAN (R 3.6.2)
 SummarizedExperiment                1.16.1   2019-12-19 [1] Bioconductor  
 testthat                            2.3.2    2020-03-02 [1] CRAN (R 3.6.2)
 tibble                              2.1.3    2019-06-06 [1] CRAN (R 3.6.2)
 tidyselect                          1.0.0    2020-01-27 [1] CRAN (R 3.6.2)
 TxDb.Hsapiens.UCSC.hg19.knownGene * 3.2.2    2020-03-27 [1] Bioconductor  
 usethis                             1.5.1    2019-07-04 [1] CRAN (R 3.6.2)
 vctrs                               0.2.4    2020-03-10 [1] CRAN (R 3.6.2)
 withr                               2.1.2    2018-03-15 [1] CRAN (R 3.6.2)
 XML                                 3.99-0.3 2020-01-20 [1] CRAN (R 3.6.2)
 xtable                              1.8-4    2019-04-21 [1] CRAN (R 3.6.2)
 XVector                             0.26.0   2019-10-29 [1] Bioconductor  
 yaml                                2.2.1    2020-02-01 [1] CRAN (R 3.6.2)
 zlibbioc                            1.32.0   2019-10-29 [1] Bioconductor  

[1] /usr/local/lib/R/site-library
[2] /usr/local/lib/R/library
```

**Comment by jakalssj3** [comment] 2021-06-11 16:20
> Do you get the same error with just library(annotatr)?

Unfortunately, I get the same error with a fresh R session and only this single library loaded.

**Comment by rcavalcante** [comment] 2021-06-11 16:25
Interesting...

I'd be curious to see the result of your session info (preferably `devtools::session_info()` because it gets alphabetized). I bet there's some dependency that's different between us.

**Comment by jakalssj3** [comment] 2021-06-11 16:27
Here is a more extensive log:

```
> library(annotatr)
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Loading required package: AnnotationDbi
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.
```

```
> annotations <- c("hg19_cpgs","hg19_genes_promoters", "hg19_basicgenes")
> promoters.GR <- annotatr::build_annotations(genome='hg19', annotations=c(annotations[2]))
Loading required package: GenomicFeatures
'select()' returned 1:1 mapping between keys and columns
Building promoters...

> cpgs.GR <- annotatr::build_annotations(genome='hg19', annotations=c(annotations[1]))
Error in UseMethod("filter_") :
  no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
```

```
> devtools::session_info()
Error in get(genname, envir = envir) : object 'testthat_print' not found
Failed to create bus connection: No such file or directory
─ Session info ──────────────────────────────────────────
 setting  value
 version  R version 3.6.3 (2020-02-29)
 os       Ubuntu 18.04 LTS
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  C.UTF-8
 ctype    C.UTF-8
 tz       Etc/UTC
 date     2021-06-11

─ Packages ───────────────────────────────────────────
 package                           * version  date       lib source
 AnnotationDbi                     * 1.48.0   2019-10-29 [1] Bioconductor
 AnnotationHub                       2.18.0   2019-10-29 [1] Bioconductor
 annotatr                          * 1.12.1   2019-11-12 [1] Bioconductor
 askpass                             1.1      2019-01-13 [2] CRAN (R 3.6.3)
 assertthat                          0.2.1    2019-03-21 [2] CRAN (R 3.6.3)
 Biobase                           * 2.46.0   2019-10-29 [2] Bioconductor
 BiocFileCache                       1.10.2   2019-11-08 [1] Bioconductor
 BiocGenerics                      * 0.32.0   2019-10-29 [1] Bioconductor
 BiocManager                         1.30.15  2021-05-11 [1] CRAN (R 3.6.3)
 BiocParallel                        1.20.1   2019-12-21 [1] Bioconductor
 BiocVersion                         3.10.1   2019-06-06 [2] Bioconductor
 biomaRt                             2.42.1   2020-03-26 [1] Bioconductor
 Biostrings                          2.54.0   2019-10-29 [1] Bioconductor
 bit                                 4.0.4    2020-08-04 [1] CRAN (R 3.6.3)
 bit64                               4.0.5    2020-08-30 [1] CRAN (R 3.6.3)
 bitops                              1.0-6    2013-08-17 [2] CRAN (R 3.6.3)
 blob                                1.2.1    2020-01-20 [1] CRAN (R 3.6.3)
 BSgenome                            1.54.0   2019-10-29 [1] Bioconductor
 callr                               3.7.0    2021-04-20 [1] CRAN (R 3.6.3)
 cli                                 2.5.0    2021-04-26 [1] CRAN (R 3.6.3)
 colorspace                          1.4-1    2019-03-18 [2] CRAN (R 3.6.3)
 crayon                              1.4.1    2021-02-08 [1] CRAN (R 3.6.3)
 curl                                4.3      2019-12-02 [2] CRAN (R 3.6.3)
 DBI                                 1.1.0    2019-12-15 [2] CRAN (R 3.6.3)
 dbplyr                              2.1.1    2021-04-06 [1] CRAN (R 3.6.3)
 DelayedArray                        0.12.3   2020-04-09 [1] Bioconductor
 desc                                1.2.0    2018-05-01 [2] CRAN (R 3.6.3)
 devtools                            2.3.2    2020-09-18 [1] CRAN (R 3.6.3)
 digest                              0.6.25   2020-02-23 [2] CRAN (R 3.6.3)
 dplyr                               1.0.6    2021-05-05 [1] CRAN (R 3.6.3)
 ellipsis                            0.3.2    2021-04-29 [1] CRAN (R 3.6.3)
 fansi                               0.4.2    2021-01-15 [1] CRAN (R 3.6.3)
 fastmap                             1.1.0    2021-01-25 [1] CRAN (R 3.6.3)
 fs                                  1.4.2    2020-06-30 [1] CRAN (R 3.6.3)
 generics                            0.1.0    2020-10-31 [1] CRAN (R 3.6.3)
 GenomeInfoDb                      * 1.22.1   2020-03-27 [1] Bioconductor
 GenomeInfoDbData                    1.2.2    2020-08-23 [2] Bioconductor
 GenomicAlignments                   1.22.1   2019-11-12 [1] Bioconductor
 GenomicFeatures                   * 1.38.2   2020-02-15 [1] Bioconductor
 GenomicRanges                     * 1.38.0   2019-10-29 [1] Bioconductor
 ggplot2                             3.3.3    2020-12-30 [1] CRAN (R 3.6.3)
 glue                                1.4.1    2020-05-13 [2] CRAN (R 3.6.3)
 gtable                              0.3.0    2019-03-25 [2] CRAN (R 3.6.3)
 hms                                 1.1.0    2021-05-17 [1] CRAN (R 3.6.3)
 htmltools                           0.5.1.1  2021-01-22 [1] CRAN (R 3.6.3)
 httpuv                              1.5.3.1  2020-05-26 [1] CRAN (R 3.6.3)
 httr                                1.4.2    2020-07-20 [2] CRAN (R 3.6.3)
 interactiveDisplayBase              1.24.0   2019-10-29 [1] Bioconductor
 IRanges                           * 2.20.2   2020-01-13 [2] Bioconductor
 later                               1.0.0    2019-10-04 [1] CRAN (R 3.6.3)
 lattice                             0.20-41  2020-04-02 [4] CRAN (R 3.6.3)
 lifecycle                           1.0.0    2021-02-15 [1] CRAN (R 3.6.3)
 magrittr                            1.5      2014-11-22 [2] CRAN (R 3.6.3)
 Matrix                              1.2-18   2019-11-27 [4] CRAN (R 3.6.1)
 matrixStats                         0.56.0   2020-03-13 [1] CRAN (R 3.6.3)
 memoise                             1.1.0    2017-04-21 [2] CRAN (R 3.6.3)
 mime                                0.9      2020-02-04 [2] CRAN (R 3.6.3)
 munsell                             0.5.0    2018-06-12 [2] CRAN (R 3.6.3)
 openssl                             1.4.2    2020-06-27 [2] CRAN (R 3.6.3)
 org.Hs.eg.db                      * 3.10.0   2020-07-13 [1] Bioconductor
 pillar                              1.6.1    2021-05-16 [1] CRAN (R 3.6.3)
 pkgbuild                            1.1.0    2020-07-13 [2] CRAN (R 3.6.3)
 pkgconfig                           2.0.3    2019-09-22 [2] CRAN (R 3.6.3)
 pkgload                             1.1.0    2020-05-29 [2] CRAN (R 3.6.3)
 plyr                                1.8.6    2020-03-03 [2] CRAN (R 3.6.3)
 prettyunits                         1.1.1    2020-01-24 [2] CRAN (R 3.6.3)
 processx                            3.5.2    2021-04-30 [1] CRAN (R 3.6.3)
 progress                            1.2.2    2019-05-16 [1] CRAN (R 3.6.3)
 promises                            1.1.0    2019-10-04 [1] CRAN (R 3.6.3)
 ps                                  1.3.4    2020-08-11 [2] CRAN (R 3.6.3)
 purrr                               0.3.4    2020-04-17 [2] CRAN (R 3.6.3)
 R6                                  2.4.1    2019-11-12 [2] CRAN (R 3.6.3)
 rappdirs                            0.3.1    2016-03-28 [2] CRAN (R 3.6.3)
 Rcpp                                1.0.6    2021-01-15 [1] CRAN (R 3.6.3)
 RCurl                               1.98-1.2 2020-04-18 [1] CRAN (R 3.6.3)
 readr                               1.3.1    2018-12-21 [1] CRAN (R 3.6.3)
 regioneR                            1.18.1   2020-01-14 [1] Bioconductor
 remotes                             2.2.0    2020-07-21 [1] CRAN (R 3.6.3)
 reshape2                            1.4.4    2020-04-09 [2] CRAN (R 3.6.3)
 rlang                               0.4.10   2020-12-30 [1] CRAN (R 3.6.3)
 rprojroot                           2.0.2    2020-11-15 [1] CRAN (R 3.6.3)
 Rsamtools                           2.2.3    2020-02-23 [1] Bioconductor
 RSQLite                             2.2.7    2021-04-22 [1] CRAN (R 3.6.3)
 rstudioapi                          0.11     2020-02-07 [2] CRAN (R 3.6.3)
 rtracklayer                         1.46.0   2019-10-29 [1] Bioconductor
 S4Vectors                         * 0.24.4   2020-04-09 [1] Bioconductor
 scales                              1.1.1    2020-05-11 [2] CRAN (R 3.6.3)
 sessioninfo                         1.1.1    2018-11-05 [1] CRAN (R 3.6.3)
 shiny                               1.6.0    2021-01-25 [1] CRAN (R 3.6.3)
 stringi                             1.4.6    2020-02-17 [2] CRAN (R 3.6.3)
 stringr                             1.4.0    2019-02-10 [2] CRAN (R 3.6.3)
 SummarizedExperiment                1.16.1   2019-12-19 [1] Bioconductor
 testthat                            2.3.2    2020-03-02 [2] CRAN (R 3.6.3)
 tibble                              3.1.2    2021-05-16 [1] CRAN (R 3.6.3)
 tidyselect                          1.1.0    2020-05-11 [2] CRAN (R 3.6.3)
 TxDb.Hsapiens.UCSC.hg19.knownGene * 3.2.2    2020-05-29 [1] Bioconductor
 usethis                             2.0.1    2021-02-10 [1] CRAN (R 3.6.3)
 utf8                                1.1.4    2018-05-24 [2] CRAN (R 3.6.3)
 vctrs                               0.3.8    2021-04-29 [1] CRAN (R 3.6.3)
 withr                               2.4.1    2021-01-26 [1] CRAN (R 3.6.3)
 XML                                 3.99-0   2020-07-24 [1] local
 xtable                              1.8-4    2019-04-21 [1] CRAN (R 3.6.3)
 XVector                             0.26.0   2019-10-29 [2] Bioconductor
 yaml                                2.2.1    2020-02-01 [1] CRAN (R 3.6.3)
 zlibbioc                            1.32.0   2019-10-29 [2] Bioconductor
```

**Comment by jakalssj3** [comment] 2021-06-11 16:50
I've tried several things now, including restarting R, reinstalling annotatr and still on selected annotation classes the same error appears:

```
> annots = c('hg19_cpgs', 'hg19_basicgenes', 'hg19_genes_intergenic')
> annotations = build_annotations(genome = 'hg19', annotations = annots)
'select()' returned 1:1 mapping between keys and columns
Building promoters...
Building 1to5kb upstream of TSS...
Building intergenic...
Building 5UTRs...
Building 3UTRs...
Building exons...
Building introns...
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
```

**Comment by rcavalcante** [comment] 2021-06-11 16:53
I think this is related to a major version difference in the `tibble` package. You have 3.1.2 and I have 2.1.3.

I'm going to update my `tidyverse` install in the image and see if I can then reproduce.

**Comment by rcavalcante** [comment] 2021-06-11 16:56
Bingo, that's the issue.

I'll have to wait until next week to look into this in more detail. I'll keep you updated. Thanks for the quick replies.

**Comment by jakalssj3** [comment] 2021-06-11 16:58
Great, thanks for tracking the issue so fast!

**Comment by rcavalcante** [comment] 2021-06-22 18:21
Sorry for the delay, but I had to wrap up some work things before going on vacation. I will be able to get to this at the beginning of July.

**Comment by rcavalcante** [comment] 2021-07-12 15:28
Upon further investigation, it actually looks like this is an issue with the `AnnotationHub` package and the updated `tibble` (or `tidyverse`) package. In the docker image I have for Bioconductor 3.10, I updated `tidyverse` to your versions and encountered an issue at the line:

```
ah = AnnotationHub::AnnotationHub()
```

So this is a much deeper dependency compatibility issue that falls outside the scope of `annotatr` proper. I hate when the solution to problems like this is "Update your version of R," but I think that's the solution here. When I use a fresh Bioconductor 3.13 docker image I don't get that error.

For now I'll close this.

**Closed as completed by rcavalcante** 2021-07-12 15:28 UTC
